// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// IM4ECpp
List IM4ECpp(Function oneIM4E, NumericMatrix train_xx, NumericVector train_yy, double epsilon, double sig, double lambda, int max_iter, bool removesmall);
RcppExport SEXP _Immigrate_IM4ECpp(SEXP oneIM4ESEXP, SEXP train_xxSEXP, SEXP train_yySEXP, SEXP epsilonSEXP, SEXP sigSEXP, SEXP lambdaSEXP, SEXP max_iterSEXP, SEXP removesmallSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Function >::type oneIM4E(oneIM4ESEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type train_xx(train_xxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type train_yy(train_yySEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type sig(sigSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< bool >::type removesmall(removesmallSEXP);
    rcpp_result_gen = Rcpp::wrap(IM4ECpp(oneIM4E, train_xx, train_yy, epsilon, sig, lambda, max_iter, removesmall));
    return rcpp_result_gen;
END_RCPP
}
// imIM4ECpp
List imIM4ECpp(Function oneimIM4E, NumericMatrix train_xx, NumericVector train_yy, double epsilon, double sig, double rho, double lambda, int max_iter, bool removesmall);
RcppExport SEXP _Immigrate_imIM4ECpp(SEXP oneimIM4ESEXP, SEXP train_xxSEXP, SEXP train_yySEXP, SEXP epsilonSEXP, SEXP sigSEXP, SEXP rhoSEXP, SEXP lambdaSEXP, SEXP max_iterSEXP, SEXP removesmallSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Function >::type oneimIM4E(oneimIM4ESEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type train_xx(train_xxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type train_yy(train_yySEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type sig(sigSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< bool >::type removesmall(removesmallSEXP);
    rcpp_result_gen = Rcpp::wrap(imIM4ECpp(oneimIM4E, train_xx, train_yy, epsilon, sig, rho, lambda, max_iter, removesmall));
    return rcpp_result_gen;
END_RCPP
}
// ImmigrateCpp
List ImmigrateCpp(Function oneImmigrate, NumericMatrix train_xx, NumericVector train_yy, double epsilon, double sig, double lambda, int max_iter, bool removesmall);
RcppExport SEXP _Immigrate_ImmigrateCpp(SEXP oneImmigrateSEXP, SEXP train_xxSEXP, SEXP train_yySEXP, SEXP epsilonSEXP, SEXP sigSEXP, SEXP lambdaSEXP, SEXP max_iterSEXP, SEXP removesmallSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Function >::type oneImmigrate(oneImmigrateSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type train_xx(train_xxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type train_yy(train_yySEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type sig(sigSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< bool >::type removesmall(removesmallSEXP);
    rcpp_result_gen = Rcpp::wrap(ImmigrateCpp(oneImmigrate, train_xx, train_yy, epsilon, sig, lambda, max_iter, removesmall));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Immigrate_IM4ECpp", (DL_FUNC) &_Immigrate_IM4ECpp, 8},
    {"_Immigrate_imIM4ECpp", (DL_FUNC) &_Immigrate_imIM4ECpp, 9},
    {"_Immigrate_ImmigrateCpp", (DL_FUNC) &_Immigrate_ImmigrateCpp, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_Immigrate(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
