# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

IM4ECpp <- function(oneIM4E, train_xx, train_yy, epsilon = 0.01, sig = 1, lambda = 1, max_iter = 10L, removesmall = FALSE) {
    .Call('_Immigrate_IM4ECpp', PACKAGE = 'Immigrate', oneIM4E, train_xx, train_yy, epsilon, sig, lambda, max_iter, removesmall)
}

imIM4ECpp <- function(oneimIM4E, train_xx, train_yy, epsilon = 0.01, sig = 1, rho = 1, lambda = 1, max_iter = 10L, removesmall = FALSE) {
    .Call('_Immigrate_imIM4ECpp', PACKAGE = 'Immigrate', oneimIM4E, train_xx, train_yy, epsilon, sig, rho, lambda, max_iter, removesmall)
}

ImmigrateCpp <- function(oneImmigrate, train_xx, train_yy, epsilon = 0.01, sig = 1, lambda = 1, max_iter = 10L, removesmall = FALSE) {
    .Call('_Immigrate_ImmigrateCpp', PACKAGE = 'Immigrate', oneImmigrate, train_xx, train_yy, epsilon, sig, lambda, max_iter, removesmall)
}

